---
    - name: Copy ~/.zshrc
      copy:
        src: zshrc.sh
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"

    - name: Create ~/.functions directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.functions"
        state: directory

    - name: Copy zsh functions to ~/.functions
      copy:
        src: "{{ item }}"
        dest: "{{ lookup('env', 'HOME') }}/.functions/"
      with_fileglob:
        - "files/functions/*"

    - git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/"
        update: yes

    - name: Create ~/.oh-my-zsh/custom/themes directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes"
        state: directory

    - git:
        repo: https://github.com/denysdovhan/spaceship-prompt.git
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship-prompt"
        depth: 1
        update: yes

    - name: Symlink spaceship .oh-my-zsh/custom/themes/spaceship.zsh-theme
      file:
        src: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
        dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
        state: link

    - name: check if /bin/zsh file exists
      stat: 
        path: /bin/zsh
      register: zsh_file
        
    - name: "Install zsh. Run 'chsh -s /bin/zsh' to set zsh as default shell"
      homebrew:
        name: zsh
        state: latest
        update_homebrew: yes
      when: zsh_file.stat.exists == false      

    - name: check if ~/Library/Fonts/ter-powerline-x12b.pcf.gz exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/Library/Fonts/ter-powerline-x12b.pcf.gz"
      register: powerline_file

    - name: Download powerline fonts (need "Fira Mono for Powerline")
      git:
        repo: https://github.com/powerline/fonts.git
        dest: "{{ lookup('env', 'HOME') }}/fonts"
        version: e80e3eb
      when: powerline_file.stat.exists == false

    - name: Install fonts
      command:
        chdir: "{{ lookup('env', 'HOME') }}/fonts"
        cmd: ./install.sh
      when: powerline_file.stat.exists == false

    - name: Copy .hyper.js to ~/.hyper.js
      copy:
        src: ".hyper.js"
        dest: "{{ lookup('env', 'HOME') }}/.hyper.js"

    - name: "Install Hyper terminal"
      homebrew_cask:
        name: hyper
        state: upgraded
        greedy: yes
        update_homebrew: yes